# Generated by Django 5.0 on 2023-12-13 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onetoone', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_id',
            name='student_id',
            field=models.CharField(max_length=10),
        ),
    ]
