# Generated by Django 5.0 on 2023-12-14 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Singer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('lan', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Sub_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('number', models.IntegerField()),
                ('email', models.EmailField(max_length=40)),
                ('city', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_id', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(max_length=20)),
                ('movie', models.CharField(max_length=20)),
                ('song_type', models.CharField(max_length=20)),
                ('song_duration', models.CharField(max_length=20)),
                ('singer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gaanaapp.singer')),
            ],
        ),
        migrations.CreateModel(
            name='Song_play',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singer', models.ManyToManyField(to='Gaanaapp.singer')),
                ('sub_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gaanaapp.sub_detail')),
            ],
        ),
        migrations.AddField(
            model_name='sub_detail',
            name='token',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Gaanaapp.token'),
        ),
    ]
