# Generated by Django 5.0 on 2023-12-14 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gaanaapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='singer',
            old_name='lan',
            new_name='lang',
        ),
    ]
