# Generated by Django 5.0 on 2023-12-14 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gaanaapp', '0002_rename_lan_singer_lang'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='singer',
            name='lang',
        ),
    ]
